### ISSUE TITLE
about the mmdetect's version of DynamicRCNN?

### ISSUE THREAD

**Issue by CS-Jackson** [hkzhang95/DynamicRCNN#4]
Hi, thanks for this impressive work. I was wondering when do you release the mmdetect's version?

**Comment by hkzhang95** [comment]
It is a little awkward that I implemented Dynamic R-CNN based on MMDetection v1.1. Recently MMDetection is already upgraded to v2.0. Since this version is not compatible with the 1.1 version, the codes and trained models can not be used directly. So I need some time to re-train the strongest model, or I will release an older version instead.

**Comment by CS-Jackson** [comment]
Glad to hear that. Thanks a lot!

**Comment by hkzhang95** [comment]
Hi, I have released an implementation of Dynamic R-CNN based on MMDetection V1.1 at this [link](https://github.com/hkzhang95/DynamicRCNN-mmdetV1.1/tree/master/configs/dynamic_rcnn). I also provide the trained model for `Dynamic R-CNN*(50.1% AP)`. You can have a look if you are interested.

I will also consider releasing a new version by making a pull request to the latest official codebase if I have time.

**Comment by hkzhang95** [comment]
@CS-Jackson Now Dynamic R-CNN has been merged into the official MMDetection codebase.
